"""Generate src/skill/SkillEnumIdTable.inc from Ref/eAthena_src_2011/map/skill.h enum e_skill."""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
SKILL_H = ROOT / "Ref" / "eAthena_src_2011" / "map" / "skill.h"
OUT = ROOT / "src" / "skill" / "SkillEnumIdTable.inc"


def main() -> None:
    text = SKILL_H.read_text(encoding="utf-8", errors="ignore")
    m = re.search(r"enum e_skill\s*\{(.*?)\n\};", text, re.S)
    if not m:
        raise SystemExit("e_skill enum not found")
    body = m.group(1)
    cur = None
    pairs: list[tuple[int, str]] = []
    for raw in body.splitlines():
        line = raw.strip().split("//")[0].strip()
        if not line:
            continue
        for part in line.split(","):
            part = part.strip()
            if not part:
                continue
            if "=" in part:
                name, val = part.split("=", 1)
                name = name.strip()
                cur = int(val.strip())
                pairs.append((cur, name))
                cur += 1
            else:
                if cur is None:
                    cur = 1
                pairs.append((cur, part))
                cur += 1

    lines = [
        "// Generated by tools/gen_skill_enum_table.py — IDs match "
        "Ref/eAthena_src_2011/map/skill.h enum e_skill.",
        "struct SkillEnumEntry { int id; const char* name; };",
        "static const SkillEnumEntry kSkillEnumEntries[] = {",
    ]
    for sid, nm in pairs:
        lines.append(f'    {{{sid}, "{nm}"}},')
    lines.append("};")
    lines.append(
        "static constexpr size_t kSkillEnumEntriesCount = "
        "sizeof(kSkillEnumEntries) / sizeof(kSkillEnumEntries[0]);"
    )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(pairs)} entries)")


if __name__ == "__main__":
    main()
